export { default as OnBoardingScreen } from './Auth/OnBoarding';
export { default as LoginScreen } from './Auth/Login';
export { default as SignUpScreen } from './Auth/SignUp';
export { default as DashboardScreen } from './dashboard/Dashboard';
export { default as ProfileScreen } from './dashboard/Profile';
export { default as SearchScreen } from './dashboard/Search';
export { default as TicketScreen } from './dashboard/Ticket';
export { default as TestScreen } from './test/Test';
export { default as ProfileEditScreen } from './dashboard/ProfileEdit';
