export { default as OnBoardingScreen } from './auth/OnBoarding';
export { default as LoginScreen } from './auth/Login';
export { default as SignUpScreen } from './auth/SignUp';
export { default as DashboardScreen } from './dashboard/Dashboard';
export { default as ProfileScreen } from './dashboard/Profile';
export { default as SearchScreen } from './dashboard/Search';
export { default as TicketScreen } from './dashboard/Ticket';
export { default as TestScreen } from './test/Test';
export { default as EditProfileScreen } from './dashboard/EditProfile';
