const MAIN = {
  ONBOARDING: 'ON_BOARDING',
  LOGIN: 'LOGIN_SCREEN',
  SIGN_UP: 'SIGN_UP_SCREEN',
  DASHBOARD: 'DASHBOARD_SCREEN',
  TEST: 'TEST_SCREEN',
  PROFILE: 'PROFILE_SCREEN',
};

export { MAIN };
